/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.yzd3008.geektools;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        GeekServerApp classUnderTest = new GeekServerApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
