/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.yzd3008.geektools;

import cn.yzd3008.geektools.server.GeekServer;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@Slf4j
@Getter
public class GeekServerApp {

    @Autowired
    private GeekServer server;

    public static void main(String[] args) {
        SpringApplication.run(GeekServerApp.class, args);
    }
}
